#Dockerfile-Multistage
FROM maven:3.9.5-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests


FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/bankapp.jar bankapp.jar
EXPOSE 8080
ENTRYPOINT["java", "-jar", "bankapp.jar"]
